#include "codegen/codegen.hpp"
#include <iostream>
#include <fstream>
void emitSycl(const IntegratorIR& ir, const BackendIR& backend, std::ostream& out) {
    out << "// Generated by PhysCC - SYCL Universal Backend for Intel Iris Xe\n";
    out << "#include <sycl/sycl.hpp>\n";
    out << "#include <iostream>\n";
    out << "#include <vector>\n";
    out << "#include <cmath>\n";
    out << "#include <fstream>\n";
    out << "#include <chrono>\n\n";

    out << "int main() {\n";
    out << "    const int N = 512;\n";
    out << "    const float dt = " << ir.dt << "f;\n";
    out << "    const int T = 2000;\n";
    out << "    const int border = 20; // Absorbing layer thickness\n\n";

    out << "    sycl::queue q(sycl::default_selector_v);\n";
    out << "    std::cout << \"[SYCL] Running on: \" << q.get_device().get_info<sycl::info::device::name>() << std::endl;\n\n";

    out << "    std::vector<float> h_u(N*N, 0.0f), h_v(N*N, 0.0f);\n";
    out << "    // Gaussian Initialization\n";
    out << "    for(int i=0; i<N; ++i) {\n";
    out << "        for(int j=0; j<N; ++j) {\n";
    out << "            float dx = i - N/2.0f; float dy = j - N/2.0f;\n";
    out << "            if (std::sqrt(dx*dx + dy*dy) < 30.0f)\n";
    out << "                h_u[i*N+j] = std::exp(-(dx*dx + dy*dy) / 400.0f);\n";
    out << "        }\n";
    out << "    }\n\n";

    out << "    sycl::buffer<float, 2> buf_u(h_u.data(), sycl::range<2>(N, N));\n";
    out << "    sycl::buffer<float, 2> buf_v(h_v.data(), sycl::range<2>(N, N));\n";
    out << "    sycl::buffer<float, 2> buf_u_new(sycl::range<2>(N, N));\n";
    out << "    sycl::buffer<float, 2> buf_v_new(sycl::range<2>(N, N));\n\n";

    out << "    auto start = std::chrono::high_resolution_clock::now();\n\n";

    out << "    for(int t=0; t<T; ++t) {\n";
    out << "        q.submit([&](sycl::handler& h) {\n";
    out << "            auto u = buf_u.get_access<sycl::access::mode::read>(h);\n";
    out << "            auto v = buf_v.get_access<sycl::access::mode::read>(h);\n";
    out << "            auto u_n = buf_u_new.get_access<sycl::access::mode::discard_write>(h);\n";
    out << "            auto v_n = buf_v_new.get_access<sycl::access::mode::discard_write>(h);\n\n";

    out << "            h.parallel_for(sycl::range<2>(N, N), [=](sycl::id<2> item) {\n";
    out << "                int i = item[0]; int j = item[1];\n";
    out << "                if (i > 0 && i < N-1 && j > 0 && j < N-1) {\n";
    out << "                    // Absorbing Boundary Condition (Sponge Layer)\n";
    out << "                    float damping = 1.0f;\n";
    out << "                    if (i < border) damping *= (float)i/border;\n";
    out << "                    else if (i > N-border-1) damping *= (float)(N-i-1)/border;\n";
    out << "                    if (j < border) damping *= (float)j/border;\n";
    out << "                    else if (j > N-border-1) damping *= (float)(N-j-1)/border;\n\n";

    out << "                    float lap = u[i+1][j] + u[i-1][j] + u[i][j+1] + u[i][j-1] - 4.0f*u[i][j];\n";
    out << "                    u_n[i][j] = (u[i][j] + v[i][j] * dt) * damping;\n";
    out << "                    v_n[i][j] = (v[i][j] + (0.5f * lap) * dt) * damping;\n";
    out << "                } else {\n";
    out << "                    u_n[i][j] = 0.0f; v_n[i][j] = 0.0f;\n";
    out << "                }\n";
    out << "            });\n";
    out << "        });\n";
    out << "        std::swap(buf_u, buf_u_new);\n";
    out << "        std::swap(buf_v, buf_v_new);\n";
    out << "    }\n";
    out << "    q.wait();\n\n";

    out << "    auto end = std::chrono::high_resolution_clock::now();\n";
    out << "    std::chrono::duration<double> diff = end - start;\n";
    out << "    double updates = (double)N * N * T / 1e9;\n";
    out << "    std::cout << \"Simulation Finished in: \" << diff.count() << \"s\" << std::endl;\n";
    out << "    std::cout << \"Performance: \" << updates / diff.count() << \" GigaUpdates/s\" << std::endl;\n\n";
    out << "    // Export final state for visualization\n";
out << "    sycl::host_accessor u_final(buf_u, sycl::read_only);\n";
out << "    std::ofstream f(\"data_final.csv\");\n";
out << "    for(int i=0; i<N; ++i) {\n";
out << "        for(int j=0; j<N; ++j) {\n";
out << "            f << u_final[i][j] << (j == N-1 ? \"\" : \",\");\n";
out << "        }\n";
out << "        f << \"\\n\";\n";
out << "    }\n";
out << "    std::cout << \"[IO] Final state saved to data_final.csv\" << std::endl;\n";
    out << "    return 0;\n";
    out << "}\n";
}
