/*
 * PhysCC - Domain-Specific Compiler for Physics Simulations
 * Copyright (C) 2026  Nikos Pappas
 * * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */
#include "codegen/codegen.hpp"
#include <iostream>
#include <vector>
#include <string>

void emitCuda(const IntegratorIR& ir, const BackendIR& backend, std::ostream& out) {
    out << "// Generated by PhysCC - CUDA High-Performance Backend\n";
    out << "#include <cuda_runtime.h>\n#include <iostream>\n#include <vector>\n#include <fstream>\n#include <cmath>\n\n";

    // 1. The CUDA Kernel
    out << "__global__ void wave_kernel(double* u, double* v, double* u_new, double* v_new, int N, double dt) {\n";
    out << "    int j = blockIdx.x * blockDim.x + threadIdx.x;\n";
    out << "    int i = blockIdx.y * blockDim.y + threadIdx.y;\n\n";
    out << "    if (i > 0 && i < N-1 && j > 0 && j < N-1) {\n";
    out << "        int idx = i * N + j;\n";
    out << "        double lap_u = u[idx+1] + u[idx-1] + u[(i+1)*N+j] + u[(i-1)*N+j] - 4.0*u[idx];\n";
    out << "        u_new[idx] = u[idx] + v[idx] * dt;\n";
    out << "        v_new[idx] = v[idx] + (0.5 * lap_u) * dt;\n";
    out << "    }\n";
    out << "}\n\n";

    out << "int main() {\n";
    out << "    const int N = 512;\n";
    out << "    const double dt = " << ir.dt << ";\n";
    out << "    const int T = 5000;\n";
    out << "    size_t size = N * N * sizeof(double);\n\n";

    // 2. Memory Allocation (Host & Device)
    out << "    double *h_u = (double*)malloc(size);\n";
    out << "    double *d_u, *d_v, *d_u_new, *d_v_new;\n";
    out << "    cudaMalloc(&d_u, size); cudaMalloc(&d_v, size);\n";
    out << "    cudaMalloc(&d_u_new, size); cudaMalloc(&d_v_new, size);\n\n";

    // 3. Initialization (Gaussian Ripple)
    out << "    for(int i=0; i<N*N; ++i) h_u[i] = 0.0;\n";
    out << "    for(int i=0; i<N; ++i) for(int j=0; j<N; ++j) {\n";
    out << "        double dx = i - N/2.0; double dy = j - N/2.0;\n";
    out << "        if(std::sqrt(dx*dx + dy*dy) < 20) h_u[i*N+j] = std::exp(-(dx*dx+dy*dy)/400.0);\n";
    out << "    }\n";
    out << "    cudaMemcpy(d_u, h_u, size, cudaMemcpyHostToDevice);\n";
    out << "    cudaMemset(d_v, 0, size);\n\n";

    // 4. Time Loop
    out << "    dim3 threads(16, 16);\n";
    out << "    dim3 blocks(N/16, N/16);\n";
    out << "    for(int t=0; t<T; ++t) {\n";
    out << "        wave_kernel<<<blocks, threads>>>(d_u, d_v, d_u_new, d_v_new, N, dt);\n";
    out << "        std::swap(d_u, d_u_new); std::swap(d_v, d_v_new);\n";
    out << "    }\n\n";

    out << "    cudaMemcpy(h_u, d_u, size, cudaMemcpyDeviceToHost);\n";
    out << "    std::cout << \"CUDA Simulation Complete.\" << std::endl;\n";
    out << "    return 0;\n}\n";
}
