/*
 * PhysCC - Domain-Specific Compiler for Physics Simulations
 * Copyright (C) 2026  [Το Όνομά Σας]
 * * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */
#include "codegen/codegen.hpp"
#include <iostream>

void emitMPI(const IntegratorIR& ir, const BackendIR& backend, std::ostream& out) {
    out << "// Generated by PhysCC - MPI Distributed Backend\n";
    out << "#include <mpi.h>\n";
    out << "#include <iostream>\n";
    out << "#include <vector>\n";
    out << "#include <cmath>\n";
    out << "#include <chrono>\n";
    out << "#include <algorithm>\n\n";

    out << "int main(int argc, char** argv) {\n";
    out << "    MPI_Init(&argc, &argv);\n";
    out << "    int rank, size;\n";
    out << "    MPI_Comm_rank(MPI_COMM_WORLD, &rank);\n";
    out << "    MPI_Comm_size(MPI_COMM_WORLD, &size);\n\n";

    out << "    const int N = 512;\n";
    out << "    const int local_rows = N / size;\n";
    out << "    const float dt = " << ir.dt << "f;\n";
    out << "    const int T = 1000;\n\n";

    out << "    std::vector<float> u((local_rows + 2) * N, 0.0f);\n";
    out << "    std::vector<float> v((local_rows + 2) * N, 0.0f);\n";
    out << "    std::vector<float> u_new((local_rows + 2) * N, 0.0f);\n";
    out << "    std::vector<float> v_new((local_rows + 2) * N, 0.0f);\n\n";

    out << "    // Initialization\n";
    out << "    int row_offset = rank * local_rows;\n";
    out << "    for(int i = 1; i <= local_rows; ++i) {\n";
    out << "        int global_i = row_offset + i - 1;\n";
    out << "        for(int j = 0; j < N; ++j) {\n";
    out << "            float dx = global_i - N/2.0f; float dy = j - N/2.0f;\n";
    out << "            if (std::sqrt(dx*dx + dy*dy) < 30.0f)\n";
    out << "                u[i*N + j] = std::exp(-(dx*dx + dy*dy) / 400.0f);\n";
    out << "        }\n";
    out << "    }\n\n";

    out << "    MPI_Barrier(MPI_COMM_WORLD);\n";
    out << "    auto start = std::chrono::high_resolution_clock::now();\n\n";

    out << "    for(int t = 0; t < T; ++t) {\n";
    out << "        // Halo Exchange\n";
    out << "        int up = (rank == 0) ? MPI_PROC_NULL : rank - 1;\n";
    out << "        int down = (rank == size - 1) ? MPI_PROC_NULL : rank + 1;\n";
    out << "        MPI_Sendrecv(&u[1*N], N, MPI_FLOAT, up, 0, &u[(local_rows+1)*N], N, MPI_FLOAT, down, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);\n";
    out << "        MPI_Sendrecv(&u[local_rows*N], N, MPI_FLOAT, down, 1, &u[0*N], N, MPI_FLOAT, up, 1, MPI_COMM_WORLD, MPI_STATUS_IGNORE);\n\n";

    out << "        // Compute\n";
    out << "        for(int i = 1; i <= local_rows; ++i) {\n";
    out << "            for(int j = 1; j < N - 1; ++j) {\n";
    out << "                float lap = u[(i+1)*N+j] + u[(i-1)*N+j] + u[i*N+j+1] + u[i*N+j-1] - 4.0f*u[i*N+j];\n";
    out << "                u_new[i*N+j] = u[i*N+j] + v[i*N+j] * dt;\n";
    out << "                v_new[i*N+j] = v[i*N+j] + (0.5f * lap) * dt;\n";
    out << "            }\n";
    out << "        }\n";
    out << "        std::swap(u, u_new);\n";
    out << "        std::swap(v, v_new);\n";
    out << "    }\n\n";

    out << "    MPI_Barrier(MPI_COMM_WORLD);\n";
    out << "    auto end = std::chrono::high_resolution_clock::now();\n\n";

    out << "    if(rank == 0) {\n";
    out << "        std::chrono::duration<double> diff = end - start;\n";
    out << "        double updates = (double)N * N * T / 1e9;\n";
    out << "        std::cout << \"[MPI] Simulation Finished in: \" << diff.count() << \"s\" << std::endl;\n";
    out << "        std::cout << \"[MPI] Performance: \" << updates / diff.count() << \" GigaUpdates/s\" << std::endl;\n";
    out << "    }\n\n";

    out << "    MPI_Finalize();\n";
    out << "    return 0;\n";
    out << "}\n";
}
