/*
 * PhysCC - Domain-Specific Compiler for Physics Simulations
 * Copyright (C) 2026  Nikos Pappas
 * * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */
#include "codegen/codegen.hpp"
#include <iostream>
#include <set>

void emitPython(const IntegratorIR& ir, std::ostream& out) {
    out << "# Generated by PhysCC - Python Backend\n";
    out << "import numpy as np\n";
    out << "import matplotlib.pyplot as plt\n\n";

    out << "def run_simulation():\n";
    out << "    N = 200\n";
    out << "    dt = 1.0\n";
    out << "    steps = 5000\n\n";

    // 1. Allocate Arrays using NumPy
    std::set<std::string> vars;
    for(auto const& [name, stencil] : ir.stencils) {
        vars.insert(name);
        out << "    " << name << " = np.ones(N)\n";
    }

    // 2. Initial Conditions (Gray-Scott Seed)
    if (vars.count("v")) {
        out << "    # Seed the reaction\n";
        out << "    v[N//2-10 : N//2+10] = 0.0\n";
        out << "    v[N//2-5  : N//2+5]  = 1.0\n\n";
    }

    out << "    print('Running Python Simulation...')\n";
    out << "    history = []\n\n";

    // 3. Time Loop
    out << "    for t in range(steps):\n";
    out << "        # Save state for plotting\n";
    out << "        if t % 50 == 0:\n";
    out << "            history.append(u.copy())\n\n";

    // 4. Compute Laplacians (Vectorized!)
    // Python/NumPy does not use loops; it uses array slicing: u[2:] - 2*u[1:-1] + u[:-2]
    out << "        # Vectorized Laplacian (Finite Difference)\n";
    if (vars.count("u")) out << "        lap_u = np.roll(u, -1) - 2*u + np.roll(u, 1)\n";
    if (vars.count("v")) out << "        lap_v = np.roll(v, -1) - 2*v + np.roll(v, 1)\n";
    
    // 5. Update Rules
    // Gray-Scott Logic (Vectorized)
    if (vars.count("u") && vars.count("v")) {
        out << "        uvv = u * v * v\n";
        out << "        u += (0.16 * lap_u - uvv + 0.035 * (1.0 - u)) * dt\n";
        out << "        v += (0.08 * lap_v + uvv - (0.035 + 0.06) * v) * dt\n";
    }

    out << "    # Plotting\n";
    out << "    plt.imshow(history, aspect='auto', cmap='inferno')\n";
    out << "    plt.colorbar(label='Concentration U')\n";
    out << "    plt.title('PhysCC Generated: Reaction-Diffusion (Python)')\n";
    out << "    plt.xlabel('Space')\n";
    out << "    plt.ylabel('Time')\n";
    out << "    plt.show()\n\n";

    out << "if __name__ == '__main__':\n";
    out << "    run_simulation()\n";
}
