/*
 * PhysCC - Domain-Specific Compiler for Physics Simulations
 * Copyright (C) 2026  Nikos Pappas
 * * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */
#include "codegen/codegen.hpp"
#include <iostream>
#include <string>

void emitAVX2(const IntegratorIR& ir, const BackendIR& backend, std::ostream& out) {
    // 🔍 Step 1: Detect the Physics Regime
    bool isComplex = false;
    for (auto const& [name, stencil] : ir.stencils) {
        for (auto const& term : stencil.terms) {
            if (term.variable == "i" || term.variable == "psi" || term.variable == "hbar") {
                isComplex = true;
                break;
            }
        }
    }

    // 🏗️ Step 2: Boilerplate and Headers
    out << "// Generated by PhysCC - Unified " << (isComplex ? "Quantum" : "Classical") << " AVX2 Backend\n";
    out << "#include <immintrin.h>\n#include <omp.h>\n#include <vector>\n#include <iostream>\n#include <chrono>\n#include <cmath>\n#include <cstdio>\n\n";

    out << "int main() {\n";
    out << "    const int N = 512; const int T = 2000; const float dt = 0.001f;\n";
    
    if (isComplex) {
        out << "    // Quantum State (De-interleaved SoA)\n";
        out << "    std::vector<float> re(N*N, 0.0f), im(N*N, 0.0f);\n";
        out << "    std::vector<float> re_new(N*N, 0.0f), im_new(N*N, 0.0f);\n";
        out << "    std::vector<float> V(N*N, 0.0f); // Potential grid\n\n";
        out << "    // Init: Gaussian Wave Packet and Potential Barrier\n";
        out << "    for(int i=0; i<N; ++i) for(int j=0; j<N; ++j) {\n";
        out << "        float x = i-N/4.0f, y = j-N/2.0f;\n";
        out << "        re[i*N+j] = std::exp(-(x*x+y*y)/200.0f);\n";
        out << "        if(j > 250 && j < 265) V[i*N+j] = 50.0f; // Tunneling Barrier\n";
        out << "    }\n";
    } else {
        out << "    // Classical State (Displacement/Velocity)\n";
        out << "    std::vector<float> u(N*N, 0.0f), v(N*N, 0.0f);\n";
        out << "    std::vector<float> u_new(N*N, 0.0f), v_new(N*N, 0.0f);\n";
        out << "    for(int i=0; i<N; ++i) for(int j=0; j<N; ++j) {\n";
        out << "        float x = i-N/2.0f, y = j-N/2.0f;\n";
        out << "        if(std::sqrt(x*x+y*y) < 20) u[i*N+j] = 1.0f;\n";
        out << "    }\n";
    }

    out << "\n    auto start = std::chrono::high_resolution_clock::now();\n";
    out << "    for(int t=0; t<T; ++t) {\n";
    out << "        #pragma omp parallel for collapse(2) schedule(static)\n";
    out << "        for(int i=1; i < N-1; ++i) {\n";
    out << "            for(int j=1; j < N-1; j += 8) {\n";
    out << "                int idx = i * N + j;\n";
    out << "                __m256 dt_v = _mm256_set1_ps(dt);\n";
    out << "                __m256 m4_v = _mm256_set1_ps(-4.0f);\n";

    if (isComplex) {
        // --- 🟢 QUANTUM PATH: TDSE with Potential ---
        out << "                __m256 r_c = _mm256_loadu_ps(&re[idx]);\n";
        out << "                __m256 i_c = _mm256_loadu_ps(&im[idx]);\n";
        out << "                __m256 pot = _mm256_loadu_ps(&V[idx]);\n\n";

        out << "                auto lap = [&](const float* data) {\n";
        out << "                    __m256 l = _mm256_add_ps(_mm256_loadu_ps(&data[idx-N]), _mm256_loadu_ps(&data[idx+N]));\n";
        out << "                    l = _mm256_add_ps(l, _mm256_add_ps(_mm256_loadu_ps(&data[idx-1]), _mm256_loadu_ps(&data[idx+1])));\n";
        out << "                    return _mm256_add_ps(l, _mm256_mul_ps(_mm256_loadu_ps(&data[idx]), m4_v));\n";
        out << "                };\n\n";

        out << "                __m256 l_r = lap(re.data());\n";
        out << "                __m256 l_i = lap(im.data());\n\n";

        out << "                // dRe/dt = -0.5*Lap(Im) + V*Im | dIm/dt = 0.5*Lap(Re) - V*Re\n";
        out << "                __m256 rhs_re = _mm256_add_ps(_mm256_mul_ps(_mm256_set1_ps(-0.5f), l_i), _mm256_mul_ps(pot, i_c));\n";
        out << "                __m256 rhs_im = _mm256_sub_ps(_mm256_mul_ps(_mm256_set1_ps(0.5f), l_r), _mm256_mul_ps(pot, r_c));\n";
        out << "                _mm256_storeu_ps(&re_new[idx], _mm256_add_ps(r_c, _mm256_mul_ps(rhs_re, dt_v)));\n";
        out << "                _mm256_storeu_ps(&im_new[idx], _mm256_add_ps(i_c, _mm256_mul_ps(rhs_im, dt_v)));\n";
    } else {
        // --- ⚪ CLASSICAL PATH: Wave Equation ---
        out << "                __m256 u_c = _mm256_loadu_ps(&u[idx]);\n";
        out << "                __m256 v_c = _mm256_loadu_ps(&v[idx]);\n";
        out << "                __m256 lap = _mm256_add_ps(_mm256_add_ps(_mm256_loadu_ps(&u[idx-N]), _mm256_loadu_ps(&u[idx+N])), \n";
        out << "                                           _mm256_add_ps(_mm256_loadu_ps(&u[idx-1]), _mm256_loadu_ps(&u[idx+1])));\n";
        out << "                lap = _mm256_add_ps(lap, _mm256_mul_ps(u_c, m4_v));\n";
        out << "                _mm256_storeu_ps(&u_new[idx], _mm256_add_ps(u_c, _mm256_mul_ps(v_c, dt_v)));\n";
        out << "                _mm256_storeu_ps(&v_new[idx], _mm256_add_ps(v_c, _mm256_mul_ps(lap, dt_v)));\n";
    }

    out << "            }\n        }\n";
    out << "        " << (isComplex ? "re.swap(re_new); im.swap(im_new);" : "u.swap(u_new); v.swap(v_new);") << "\n";
    out << "    }\n";
    
    out << "    auto end = std::chrono::high_resolution_clock::now();\n";
    out << "    std::cout << \"[PhysCC " << (isComplex ? "Quantum" : "Classical") << "] Performance: \" << (double)N*N*T/1e9 / std::chrono::duration<double>(end-start).count() << \" GUPS\\n\";\n";
    
    out << "    // 📊 Final Data Export\n";
    out << "    FILE* f = fopen(\"simulation_results.csv\", \"w\");\n";
    out << "    if (f) {\n";
    out << "        for(int i=0; i<N; ++i) {\n";
    out << "            for(int j=0; j<N; ++j) {\n";
    out << "                float val = " << (isComplex ? "(re[i*N+j]*re[i*N+j] + im[i*N+j]*im[i*N+j])" : "u[i*N+j]") << ";\n";
    out << "                fprintf(f, \"%f%s\", val, (j == N-1 ? \"\" : \",\"));\n";
    out << "            }\n";
    out << "            fprintf(f, \"\\n\");\n";
    out << "        }\n";
    out << "        fclose(f);\n";
    out << "        std::cout << \"[PhysCC] Data saved to simulation_results.csv\\n\";\n";
    out << "    }\n";
    
    out << "    return 0;\n}\n";
}
