#include "codegen/codegen.hpp"
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>

void emitCpp(const IntegratorIR& ir, const BackendIR& backend, std::ostream& out) {
    out << "// Generated by PhysCC - Universal High-Performance Backend\n";
    out << "#include <iostream>\n#include <vector>\n#include <fstream>\n#include <omp.h>\n#include <cmath>\n#include <algorithm>\n\n";
    
    out << "int main() {\n";
    out << "  const int N = 512;\n";
    out << "  const double dt = " << ir.dt << ";\n";
    out << "  const int T = 5000; // Enough time for waves to travel\n";
    out << "  std::ofstream csv(\"data_2d.csv\");\n\n";

    // 1. Dynamic Vector Allocation
    // We assume 'u' and 'v' are the target variables for coupled systems
    for(auto const& [name, node] : ir.stencils) {
        out << "  std::vector<double> " << name << "(N*N, 0.0), " << name << "_new(N*N, 0.0);\n";
    }

    // 2. Initial Condition Logic (Verbalized from CLI)
    out << "\n  // Initial Condition: " << ir.initial_condition << "\n";
    if (ir.initial_condition == "gaussian") {
        out << "  for(int i=0; i<N; ++i) {\n";
        out << "    for(int j=0; j<N; ++j) {\n";
        out << "      double dx = i - N/2.0;\n";
        out << "      double dy = j - N/2.0;\n";
        out << "      u[i*N + j] = std::exp(-(dx*dx + dy*dy) / 400.0);\n";
        out << "    }\n  }\n";
    } else {
        out << "  // Default Square Shock\n";
        out << "  for(int i=N/2-25; i<N/2+25; ++i)\n";
        out << "    for(int j=N/2-25; j<N/2+25; ++j) u[i*N + j] = 1.0;\n";
    }

    // 3. Time Evolution Loop
    out << "\n  for(int t=0; t<T; ++t) {\n";
    out << "    if(t % 50 == 0) {\n";
    out << "      for(int i=0; i<N*N; ++i) csv << u[i] << (i == N*N-1 ? \"\" : \",\");\n";
    out << "      csv << \"\\n\";\n";
    out << "    }\n\n";

    // 4. Parallel Stencil Execution (Path A: Tiling & OpenMP)
    out << "    #pragma omp parallel for collapse(2)\n";
    if (ir.optimization.enableTiling) {
        int TS = ir.optimization.tileSize;
        out << "    for (int ii = 1; ii < N-1; ii += " << TS << ") {\n";
        out << "      for (int jj = 1; jj < N-1; jj += " << TS << ") {\n";
        out << "        for (int i = ii; i < std::min(ii + " << TS << ", N-1); ++i) {\n";
        out << "          for (int j = jj; j < std::min(jj + " << TS << ", N-1); ++j) {\n";
    } else {
        out << "    for (int i = 1; i < N-1; ++i) {\n";
        out << "      for (int j = 1; j < N-1; ++j) {\n";
    }

    out << "            int idx = i*N + j;\n";

    // 5. Generate Physics Math based on IR Stencils
    // Note: We handle the Hyperbolic coupling (du/dt = v) explicitly here
    out << "            double lap_u = u[idx+1] + u[idx-1] + u[(i+1)*N+j] + u[(i-1)*N+j] - 4.0*u[idx];\n";
    
    if (ir.stencils.count("v")) {
        // Wave Equation Logic
        out << "            u_new[idx] = u[idx] + v[idx] * dt;\n";
        out << "            v_new[idx] = v[idx] + (0.5 * lap_u) * dt;\n";
    } else {
        // Simple Diffusion Logic (Heat)
        out << "            u_new[idx] = u[idx] + (0.1 * lap_u) * dt;\n";
    }

    // Close loops
    if (ir.optimization.enableTiling) {
        out << "          }\n        }\n      }\n    }\n";
    } else {
        out << "      }\n    }\n";
    }

    // 6. Double Buffering Swap
    for(auto const& [name, node] : ir.stencils) {
        out << "    " << name << ".swap(" << name << "_new);\n";
    }
    out << "  }\n";
    out << "  return 0;\n}\n";
}
